name: fix code styling

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  lint:
    uses: laravel/.github/.github/workflows/coding-standards.yml@9c15e86fffce728fb6c50ebeae24fd63e98f4d1d # main
    with:
      php: "8.3"
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: npm install

      - name: Format code
        run: npm run format

      - name: Commit formatted files
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5
        with:
          commit_message: "Fix code style"
