name: fix code styling

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  lint:
    uses: laravel/.github/.github/workflows/coding-standards.yml@9c15e86fffce728fb6c50ebeae24fd63e98f4d1d # main
    with:
      php: "8.3"
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install dependencies
        run: npm install

      - name: Format code
        run: npm run format

      - name: Commit formatted files
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: "Fix code style"
